import LoginPage from '../pages/LoginPage';
import HomePage from '../pages/HomePage';
import RegisterPage from '../pages/RegisterPage';
import ActivationPage from '../pages/ActivationPage';
import ProductsPage from '../pages/ProductsPage';
import BestSellingPage from '../pages/BestSellingPage';
import EventPage from '../pages/EventPage';
import FaqPage from '../pages/FaqPage';
import ProductDetailsPage from '../pages/ProductDetailsPage';
import ProfilePage from '../pages/ProfilePage';
import CheckoutPage from '../pages/CheckoutPage';
import PaymentPage from '../pages/PaymentPage';
import OrderSuccessPage from '../pages/OrderSuccessPage';
import ShopCreatePage from '../pages/ShopCreatePage';
import ShopLoginPage from '../pages/ShopLoginPage';
import AdminDashboardPage from '../pages/AdminDashboardPage';
import AdminUsersPage from '../pages/AdminUsersPage';
import AdminSellersPage from '../pages/AdminSellersPage';
import AdminOrdersPage from '../pages/AdminOrdersPage';
import AdminProductsPage from '../pages/AdminProductsPage';
import AdminEventsPage from '../pages/AdminEventsPage';
import AdminWithdrawPage from '../pages/AdminWithdrawPage';
import UserInbox from '../pages/UserInbox';

export { LoginPage, HomePage, RegisterPage, ActivationPage, ProductsPage, BestSellingPage, EventPage, FaqPage, ProductDetailsPage, ProfilePage, CheckoutPage, PaymentPage, OrderSuccessPage, ShopCreatePage, ShopLoginPage, AdminDashboardPage, AdminUsersPage, AdminSellersPage, AdminOrdersPage, AdminProductsPage, AdminEventsPage, AdminWithdrawPage, UserInbox };
